### ISSUE TITLE
Support for DynamoDbVersionAttribute to enable Optimistic Locking

### ISSUE THREAD

**Issue by emanodame** [oharaandrew314/dynamodb-kotlin-module#12]
I see there is no Kt annotation for DynamoDbVersionAttribute. Will you be able to add it ? Or any workarounds that can be applied to get this functionality?

**Comment by oharaandrew314** [comment]
Seems reasonable.  I'll look into adding support.

Is this a new annotation?  Or have I just never noticed it?

**Comment by emanodame** [comment]
I believe it’s been around for a year or so. There’s a few annotations that are packaged with the DDB Enhanced client package that bring useful functionality. 

Version annotation being one of them, you may also be interested in looking at DynamoDBAutoGeneratedTimestamp

**Comment by emanodame** [comment]
Also i recommend making the project more open for extension via dependency injection/ interfaces. Then it would be possible to customise and add these behaviours even if it is not fully supported. 

Apart from this , thanks for this lib. This current is blocking my current team from using it but will definitely use it once this is fixed !

**Comment by oharaandrew314** [comment]
I've rejigged the internals so that extensions are now supported.  See [this](https://github.com/oharaandrew314/dynamodb-kotlin-module/blob/master/src/test/kotlin/io/andrewohara/dynamokt/samples/BeanTableExtensions.kt#L69) sample for an example.  Make sure to register the extension to your enhanced client, like normal.
