### ISSUE TITLE
Trouble on Index creation. LSI is created instead of  GSI

### ISSUE THREAD

**Issue by sebastianfuss** [oharaandrew314/dynamodb-kotlin-module#18]
Hi 👋  I would like to create a sparse Index (GSI). The partition key of the sparse index should be the same as partition key from the table.

```kotlin
const val SPARSE_INDEX = "sparse-index"

@DynamoDbBean
data class DynamoDbItem(
    @DynamoKtPartitionKey
    @DynamoKtSecondaryPartitionKey(indexNames = [SPARSE_INDEX])
    val id: String,

    @DynamoKtSecondarySortKey(indexNames = [SPARSE_INDEX])
    val isOpen: String = true.toString(),
)

```

For Testing we use an local aws dynamodb and creating the Tables and the Indices with the extensions function from your lib. https://github.com/oharaandrew314/dynamodb-kotlin-module/blob/e671b500625fefedbe97af9cffcc71ad8716aaec/src/main/kotlin/dev/andrewohara/dynamokt/AwsSdkExtensions.kt#L13-L38

On creating a table I got the following error:
```
java.util.concurrent.CompletionException: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Local Secondary indices are not allowed on hash tables, only hash and range tables (Service: DynamoDb, Status Code: 400, Request ID: 90307536-62ed-4371-834b-9dbede710e52)
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
```

For me its not clear, why a LSI is here created. The Index should be a GSI. 
Could you give me advice how to enforce a gsi here, please? (On production there is no problem with the GSI.)
Many Thanks in advance. 🙏

**Comment by oharaandrew314** [comment]
The `TableSchema` doesn't model the information required to create indices without assumptions.   See https://github.com/aws/aws-sdk-java-v2/issues/1771#issuecomment-613126000 This is why the original SDK completely omitted the feature to create indices until recently.  The only reason `createTableWithIndices` still exists in this library is because the feature was never implemented for the async version of the table.

The issue here is that without the detailed index information, `createTableWithIndices` can only guess how the indices are supposed to look, and in this case, it guesses wrong.  In this case, the workaround is to call `DynamoDbAsyncTable.createTable(enhancedRequest: CreateTableEnhancedRequest)`, and specify the index definitions yourself.

**Comment by sebastianfuss** [comment]
Hi @oharaandrew314 thanks for your answer!
I understand that the creation is not part of this library. 👍 

But maybe it would be good solution to enhance the Annotation `DynamoKtSecondaryPartitionKey` about the information if it should be a LSI or GSI ✌️ For it seems the best place where to put this information.

**Comment by oharaandrew314** [comment]
To be clear, this library is just a plugin for the official Dynamo DB Enhanced SDK.  All it does is use a new set of kotlin-friendly annotations and reflection capabilities to generate a kotlin-friendly implementation of the official SDK's `TableSchema`.  The official `TableSchema` is what's missing the metadata, and it's what's used to create the table.  So adding the metadata to the annotations isn't good enough.

However, it may be possible to go above and beyond the interface of `TableSchema`, and provide a further enhanced `createTable` method with new metadata provided by the new annotations.  I'm not certain I want this library to have that responsibility, however.

In the meantime, [Http4k Connect](https://github.com/http4k/http4k-connect) is a pure-kotlin implementation of the AWS SDK with it's own DynamoDB mapper, and it already has these capabilities, since it relies on typesafe schemas rather than annotations.  This library only exists for those stuck with the official java SDK.  If that's not an issue for you, you may wish to check it out instead.

You can check out:
[Examples](https://github.com/http4k/http4k-connect/tree/master/amazon/dynamodb/client/src/examples/kotlin)
[A Quick Intro Video by me](https://www.youtube.com/watch?v=wq9hiEhjqCw)
